spring:
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:h2:mem:DATABASE
    driver-class-name: 'org.h2.Driver'
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  flyway:
    locations: 'classpath:db/migration,test_data'
server:
  port: 8084