spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cloud:
    kubernetes:
      enabled: false
      discovery:
        enabled: false
    discovery:
      enabled: false
  flyway:
    locations: 'classpath:db/migration,test_data'
    baseline-on-migrate: true
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace