spring:
  application:
    name: budget-service

---

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---

spring:
  cloud:
    kubernetes:
      enabled: false
      discovery:
        enabled: false
    discovery:
      enabled: false

---

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
  sql:
    init:
      continue-on-error: true