spring:
  application:
    name: rin
server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---

spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  cloud:
    discovery:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

---

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: mysql
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://172.16.0.7:3310/money-maker-test
    username: mm-app
    password: SaveMoney
    driver-class-name: com.mysql.cj.jdbc.Driver
    data:

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://172.16.0.7:3310/money-maker-test
    username: mm-app
    password: SaveMoney
    driver-class-name: com.mysql.cj.jdbc.Driver
    data:
#spring.jpa.hibernate.ddl-auto=create-drop
#jdbc:h2:test;SCHEMA=moneymaker
#spring.datasource.url=jdbc:mysql://localhost:3306/moneymaker
#spring.datasource.username=root
#spring.datasource.password=
