spring:
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:h2:mem:DATABASE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driver-class-name: 'org.h2.Driver'
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    locations: 'classpath:db/migration,test_data'
    baseline-on-migrate: true
server:
  port: 8084

---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/moneymaker
      client:
        registration:
          rin-budget-service:
            provider: keycloak
            client-id: rin-budget-service
            client-secret: 3eeef679-dac3-4092-ab78-6059244adcbf
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8081/auth/realms/moneymaker/protocol/openid-connect/token

---

spring:
  rabbitmq:
    username: test
    password: test