spring:
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://budget-service-db:5432/budgets
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: 'classpath:db/migration'
    baseline-on-migrate: true
#debug: false
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/auth/realms/moneymaker
      client:
        registration:
          budget-service:
            provider: keycloak
            client-id: budget-service
            client-secret: qu1hrthelftPL9KRtA66IUZxzGKL33lp
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://keycloak:8081/auth/realms/moneymaker/protocol/openid-connect/token