spring:
  cloud:
    discovery:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/budget
    username: keycloak
    password: password
  flyway:
    baseline-on-migrate: true
server:
  port: 8084

---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/moneymaker
      client:
        registration:
          rin-budget-service:
            provider: keycloak
            client-id: rin-budget-service
            client-secret: 4fe1721d-26a9-4d89-b7a4-04236f796726
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8081/auth/realms/moneymaker/protocol/openid-connect/token
