spring:
  cloud:
    discovery:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5435/budgets
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: 'classpath:db/migration'
    baseline-on-migrate: true
server:
  port: 8092

---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/moneymaker
      client:
        registration:
          budget-service:
            provider: keycloak
            client-id: budget-service
            client-secret: qu1hrthelftPL9KRtA66IUZxzGKL33lp
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8081/auth/realms/moneymaker/protocol/openid-connect/token
---

spring:
  rabbitmq:
    username: test
    password: test
    host: localhost
    port: 5672

---

spring:
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8079