spring:
  cloud:
    discovery:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://172.16.0.7:3306/mm_budget_dev
    username: app_user
    password: 6NSMqvSszpKq42Jf
  flyway:
    baseline-on-migrate: true
server:
  port: 8084