INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (1, 2,  'Rent / Mortgage',  '2017-01-01',  NULL, 2, 800, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (2, 2,  'Auto Loan / Lease',  '2017-01-01',  NULL, 2, 350, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (30, 10,  'Dining',  '2017-01-01',  NULL, 2, 50, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (3, 2,  'Auto Insurance',  '2017-01-01',  NULL, 2, 350, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (4, 2,  'Health Insurance',  '2017-01-01',  NULL, 2, 350, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (5, 2,  'Cable / Internet',  '2017-01-01',  NULL, 2, 102.25, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (6, 2,  'Cell Phone',  '2017-01-01',  NULL, 2, 75.32, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (7, 6,  'Groceries',  '2017-01-01',  NULL, 2, 100, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (8, 6,  'Gas',  '2017-01-01',  NULL, 2, 100, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (9, 6,  'Household Items',  '2017-01-01',  NULL, 2, 50, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (10, 7,  'Amazon Prime',  '2017-01-01',  NULL, 5, 99, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (11, 7,  'Plex',  '2017-01-01',  NULL, 2, 3.99, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (12, 7,  'Netflix',  '2017-01-01',  NULL, 2, 10.99, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (13, 7,  'Spotify',  '2017-01-01',  NULL, 2, 10.99, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (14, 7,  'Adobe',  '2017-01-01',  '2018-12-31', 2, 20.39, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (15, 7,  'Audible',  '2017-01-01',  NULL, 2, 20.39, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (16, 8,  'Rainy Day Fund',  '2017-01-01',  NULL, 2, 100, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (17, 8,  'Home Downpayment',  '2017-01-01',  NULL, 2, 1000, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (18, 8,  'Vacation',  '2017-01-01',  NULL, 2, 200, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (19, 9,  'Retirement / 401k',  '2017-01-01',  NULL, 2, 50, 1, 2);
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (20, 1,  'General',  '2017-01-01',  NULL, 2, 3000, 1, 1); -- fixed income
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (21, 2,  'General',  '2017-01-01',  NULL, 2, 50, 1, 2); -- fixed bill
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (22, 3,  'General',  '2017-01-01',  NULL, 2, 50, 1, 2); -- fixed spending
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (23, 4,  'General',  '2017-01-01',  NULL, 2, 50, 1, 1); -- flexible income
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (24, 5,  'General',  '2017-01-01',  NULL, 2, 50, 1, 2); -- flexible bill
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (25, 6,  'General',  '2017-01-01',  NULL, 2, 50, 1, 2); -- flexible spending
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (26, 7,  'General',  '2017-01-01',  NULL, 2, 50, 1, 2); -- discretionary subscription
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (27, 8,  'General',  '2017-01-01',  NULL, 2, 50, 1, 2); -- discretionary savings
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (28, 9,  'General',  '2017-01-01',  NULL, 2, 50, 1, 2); -- discretionary investment
INSERT INTO budget (budget_id,  budget_category_id,  budget_item_name,  start_date,  end_date,  frequency_type_id,  amount,  in_use, transaction_type_id) VALUES (29, 10,  'General',  '2017-01-01',  NULL, 2, 50, 1, 2); -- discretionary spending
